patches-version = "dev"
# cli-version = "dev"
enable-module-update = false

[gboard-morphe]
enabled = true
pkg-name = "com.google.android.inputmethod.latin"
app-name = "gboard"
rv-brand = "morphe"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "jasonwu1994/Gboard-patches"
excluded-patches = "'Package Rename'"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.inputmethod.latin"

[gboard-morphe-clone]
enabled = true
pkg-name = "com.google.android.inputmethod.latin"
app-name = "gboard"
rv-brand = "morphe-clone"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "jasonwu1994/Gboard-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.inputmethod.latin"

[tiktok-morphe-alt]
enabled = true
pkg-name = "com.zhiliaoapp.musically"
app-name = "tiktok"
rv-brand = "morphe-alt"
build-mode = "apk"
arch = "both"
patches-source = "hxreborn/hxreborn-tiktok-patches"
patches-version = "latest"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.zhiliaoapp.musically"

# ==========================================
# 1. Brave Origin (Stable APK + Stable Patches)
# ==========================================
[brave-origin-stable]
enabled = true
app-name = "brave-browser"
pkg-name = "com.brave.browser"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
patches-version = "latest"
cli-source = "MorpheApp/morphe-desktop"
cli-version = "latest"
github-dlurl = "https://github.com/brave/brave-browser/releases"
apkmirror-dlurl = "https://www.apkmirror.com/apk/brave-software/brave-browser"
uptodown-dlurl = "https://brave-software-brave.en.uptodown.com/android"
patcher-args = """\
  -O"Change app name"="Brave Origin" \
  -O"Custom icon"="assets/isoamoledbraveicon.png" \
  """

# ==========================================
# 2. BraveO² (Stable APK + Stable Patches + Cloned)
# ==========================================
[brave-o2-stable]
enabled = true
app-name = "brave-browser"
pkg-name = "com.brave.origin"
rv-brand = "morphe-o2"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
patches-version = "latest"
cli-source = "MorpheApp/morphe-desktop"
cli-version = "latest"
github-dlurl = "https://github.com/brave/brave-browser/releases"
apkmirror-dlurl = "https://www.apkmirror.com/apk/brave-software/brave-browser"
uptodown-dlurl = "https://brave-software-brave.en.uptodown.com/android"
included-patches = "'Default' 'Clone app'"
patcher-args = """\
  -O"Change app name"="BraveO²" \
  -O"Clone app"="com.brave.origin" \
  -O"Custom icon"="assets/isoamoledbraveicon.png" \
  """

# ==========================================
# 3. Brave Origin Dev (Stable APK + Dev Patches)
# ==========================================
[brave-origin-dev]
enabled = true
app-name = "brave-browser"
pkg-name = "com.brave.browser"
rv-brand = "morphe-dev"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-desktop"
cli-version = "dev"
github-dlurl = "https://github.com/brave/brave-browser/releases"
apkmirror-dlurl = "https://www.apkmirror.com/apk/brave-software/brave-browser"
uptodown-dlurl = "https://brave-software-brave.en.uptodown.com/android"
patcher-args = """\
  -O"Change app name"="Brave Origin Dev" \
  -O"Custom icon"="assets/isoamoledbraveicon.png" \
  """









